language: node_js
node_js:
- "stable"

notifications:
  email: false

script:
- node ./src/tests/tests/tests.js

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE gwotest;' -U postgres
